name: deploy_vote

on:
  push:
    branches: vote  

jobs: 
  deployVote:
    name: Deploy Vote in Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Setting Vars
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set REDIS_PORT=${{ secrets.REDIS_PORT }} -a is3-vote
          heroku config:set REDIS_HOST=${{ secrets.REDIS_HOST }} -a is3-vote
          heroku config:set REDIS_PASS=${{ secrets.REDIS_PASS }} -a is3-vote
      - name: Build and Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd ./vote
          heroku container:push -a is3-vote web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a is3-vote web 